### PR TITLE
Moved files into toggl package, added setup.py and updated README.md

### PR DESCRIPTION
**Pull request by pauloxnet**
Starting from PR #9  I 've updated the code to be able to install this via setuptools and permit to upload the package to pypi starting from the latest commit on master.

### CODE REVIEW

**Comment by matthewdowney** [comment]
Looks great, thank you!

**Comment by pauloxnet** [comment]
Thanks for merging.
It would great having this package on pypi.org
Have you any plans to upload your package or need some help?
Here the docs:
https://packaging.python.org/tutorials/packaging-projects/

**Comment by matthewdowney** [comment]
Feel free to do that if you'd like!

**Comment by pauloxnet** [comment]
@matthewdowney I uploaded the project on pypi.org as you proposed to help everyone to install with pip
https://pypi.org/project/TogglPy/

**Pull request merged**
