### PR TITLE
Added setup.py and updated README

### PR DESCRIPTION
**Pull request by TeePaps**
I wanted to be able to install this via setuptools

### CODE REVIEW

**Comment by tivvit** [comment]
It would be also nice to upload the package to pypi. I can see that the PR is open for a very long time. is there help needed?

**Comment by matthewdowney** [comment]
@tivvit if you feel like rebasing to get rid of merge conflicts I'll merge it.

**Comment by tivvit** [comment]
I will try ;)

**Comment by pauloxnet** [comment]
@matthewdowney I thinks this PR can be closed because PR #26 was already merged.

**Comment by tivvit** [comment]
sorry I did not particiapate. Great work.
Do you plan the pypi upload? There will be some changes in the docs after, I can take care about that.

**Pull request closed without merging**
